/* ============================================================================
   示例数据（合成） —— 静态设计示例的唯一数据源，页面不发起任何网络请求
   ----------------------------------------------------------------------------
   IP 全部取自 RFC 5737 的文档专用网段（192.0.2.0/24、198.51.100.0/24、203.0.113.0/24），
   节点名、城市、ASN、评分都是编的。字段名对齐 frontend/src/results.js 归一化后的记录
   （node / status / exit_ip / isp / is_residential / native_status / coffee_score /
   score / ipure_scores），这样第二步接真实链路时 artifact 记录可以原样喂给同一个
   渲染函数，不需要中间适配层。

   刻意覆盖了四种边界：完整、部分、失败，以及
   - score === null（IPure 没返回纯净度总分）
   - ipure_scores 里出现 -1（地区受限哨兵，不是低分）
   - ipure_scores 里出现 null（该项无数据）
   ========================================================================== */

// IPure 六项场景，顺序与 id 对齐 https://ipure.dev/docs/api 的 scenarios[].id
export const SCENARIO_LABELS = [
  ["ai", "AI"],
  ["social", "社交"],
  ["streaming", "流媒体"],
  ["gaming", "游戏"],
  ["ecommerce", "电商"],
  ["email", "邮件"],
];

export const SNAPSHOT_META = {
  // 固定值而不是 new Date()：示例每次打开都长一样，截图和比对才有可比性。
  generatedAt: "2026-09-22 11:40",
  source: "示例数据",
};

export const NODES = [
  {
    node: "东京 NTT 01",
    type: "hysteria2",
    status: "success",
    exit_ip: "192.0.2.18",
    country: "日本",
    city: "东京",
    isp: "NTT Communications",
    asn: 4713,
    company_type: "住宅宽带",
    is_residential: true,
    native_status: "原生 IP",
    is_native: true,
    coffee_score: 92,
    score: 91,
    ipure_scores: { ai: 90, social: 85, streaming: 92, gaming: 88, ecommerce: 86, email: 84 },
  },
  {
    node: "大阪 IIJ 02",
    type: "vmess",
    status: "success",
    exit_ip: "192.0.2.44",
    country: "日本",
    city: "大阪",
    isp: "Internet Initiative Japan",
    asn: 2497,
    company_type: "机房 / 托管",
    is_residential: false,
    native_status: "原生 IP",
    is_native: true,
    coffee_score: 88,
    score: 87,
    ipure_scores: { ai: 88, social: 82, streaming: 90, gaming: 85, ecommerce: 83, email: 80 },
  },
  {
    node: "新加坡 SG-01",
    type: "trojan",
    status: "success",
    exit_ip: "198.51.100.7",
    country: "新加坡",
    city: "新加坡",
    isp: "Singtel",
    asn: 3758,
    company_type: "住宅宽带",
    is_residential: true,
    native_status: "原生 IP",
    is_native: true,
    coffee_score: 86,
    score: 89,
    ipure_scores: { ai: 92, social: 88, streaming: 86, gaming: 90, ecommerce: 88, email: 86 },
  },
  {
    node: "香港 HKT-02",
    type: "shadowsocks",
    status: "success",
    exit_ip: "203.0.113.11",
    country: "中国香港",
    city: "香港",
    isp: "HKT Limited",
    asn: 4760,
    company_type: "机房 / 托管",
    is_residential: false,
    native_status: "原生 IP",
    is_native: true,
    coffee_score: 84,
    score: 82,
    ipure_scores: { ai: 84, social: 80, streaming: 83, gaming: 79, ecommerce: 81, email: 77 },
  },
  {
    node: "首尔 KT-01",
    type: "trojan",
    status: "success",
    exit_ip: "203.0.113.29",
    country: "韩国",
    city: "首尔",
    isp: "Korea Telecom",
    asn: 4766,
    company_type: "住宅宽带",
    is_residential: true,
    native_status: "原生 IP",
    is_native: true,
    coffee_score: 80,
    score: 79,
    // 电商项 -1：该地区受限，按哨兵显示成中性灰的 -1，不参与数值排序，也不被分数筛选命中
    ipure_scores: { ai: 78, social: 74, streaming: 76, gaming: 72, ecommerce: -1, email: 70 },
  },
  {
    node: "伦敦 BT-01",
    type: "hysteria2",
    status: "success",
    exit_ip: "198.51.100.120",
    country: "英国",
    city: "伦敦",
    isp: "British Telecommunications",
    asn: 2856,
    company_type: "住宅宽带",
    is_residential: true,
    native_status: "原生 IP",
    is_native: true,
    coffee_score: 78,
    score: 81,
    ipure_scores: { ai: 82, social: 79, streaming: 84, gaming: 76, ecommerce: 78, email: 75 },
  },
  {
    node: "阿姆斯特丹 LeaseWeb-01",
    type: "vmess",
    status: "success",
    exit_ip: "203.0.113.77",
    country: "荷兰",
    city: "阿姆斯特丹",
    isp: "LeaseWeb",
    asn: 28753,
    company_type: "机房 / 托管",
    is_residential: false,
    native_status: "原生 IP",
    is_native: true,
    coffee_score: 74,
    score: 72,
    ipure_scores: { ai: 73, social: 68, streaming: 75, gaming: 66, ecommerce: 70, email: 65 },
  },
  {
    node: "洛杉矶 ColoCrossing-03",
    type: "hysteria2",
    status: "partial",
    exit_ip: "198.51.100.66",
    country: "美国",
    city: "洛杉矶",
    isp: "ColoCrossing",
    asn: 36352,
    company_type: "机房 / 托管",
    is_residential: false,
    native_status: "广播 IP",
    is_native: false,
    coffee_score: 71,
    score: 64,
    // 电商是上游真值的 -1（该地区受限）、邮件是缺项：六格恒在，两者都显示 -1，成因只在 title 里区分
    ipure_scores: { ai: 70, social: 66, streaming: 72, gaming: 61, ecommerce: -1, email: null },
  },
  {
    node: "多伦多 Bell-01",
    type: "trojan",
    status: "partial",
    exit_ip: "192.0.2.150",
    country: "加拿大",
    city: "多伦多",
    isp: "Bell Canada",
    asn: 577,
    company_type: "住宅宽带",
    is_residential: true,
    native_status: "原生 IP",
    is_native: true,
    coffee_score: 69,
    // IPure 没返回纯净度总分。真实链路里这种节点被如实标记为「部分」，
    // 而不是伪造一个 0 分；砖块显示「—」并写明原因。
    score: null,
    score_note: "IPure 未返回纯净度总分",
    ipure_scores: { ai: 68, social: 64, streaming: 70, gaming: 62, ecommerce: 66, email: null },
  },
  {
    node: "法兰克福 Hetzner-01",
    type: "vmess",
    status: "partial",
    exit_ip: "192.0.2.101",
    country: "德国",
    city: "法兰克福",
    isp: "Hetzner Online",
    asn: 24940,
    company_type: "机房 / 托管",
    is_residential: false,
    native_status: "广播 IP",
    is_native: false,
    coffee_score: 63,
    score: 58,
    ipure_scores: { ai: 60, social: 55, streaming: 62, gaming: 52, ecommerce: 57, email: 54 },
  },
  {
    node: "台北 CHT-01",
    type: "shadowsocks",
    status: "failed",
    exit_ip: null,
    country: null,
    city: null,
    isp: "Chunghwa Telecom",
    asn: 3462,
    company_type: null,
    is_residential: null,
    native_status: null,
    is_native: null,
    coffee_score: null,
    score: null,
    ipure_scores: null,
    error: "Mihomo 启动后 30 秒内未建立任何可用连接",
    error_step: "节点连接",
  },
  {
    node: "悉尼 Vocus-01",
    type: "vmess",
    status: "failed",
    exit_ip: null,
    country: null,
    city: null,
    isp: "Vocus",
    asn: 4826,
    company_type: null,
    is_residential: null,
    native_status: null,
    is_native: null,
    coffee_score: null,
    score: null,
    ipure_scores: null,
    error: "握手超时：3 次尝试全部失败",
    error_step: "出口 IP 确认",
  },
];